### ISSUE TITLE
如果开启enableSeparateBuildPerCPUArchitecture，会生成多个apk，会全部上传，最终生效的是最后一个

### ISSUE THREAD

**Issue by superchenwb** [fwh1990/react-native-upload#10]
如果开启enableSeparateBuildPerCPUArchitecture，会生成多个apk，会全部上传，最终生效的是最后一个，也就是X86架构的apk，导致手机无法安装。
能不能指定上传的apk的名字呢

**Comment by fwh1990** [comment]
Hello，已经发布`2.1.0`，通过增加 --apk 进行指定上传的（单个或者多个）文件
```bash
# 具体名称
npx upload-pgy --apk=app-release.apk

# 通配
npx upload-pgy --apk=x86_64
npx upload-pgy --apk=release-[0-9]
```
名称为正则表达式或者普通字符串，README.md已经更新

**Comment by superchenwb** [comment]
非常感谢，作者真是神速！！
