### ISSUE TITLE
会不会有点跑偏呢，这工作不该是运维的吗

### ISSUE THREAD

**Issue by zisheng-ai** [fwh1990/react-native-upload#11]

**Comment by fwh1990** [comment]
运维拿来放到genkins也是完全没问题，前端提交代码，触发hook，genkins任务自动跑起来。

而且对于小公司或者个人开发者或者纯外包吧，运维也不一定会有，都是兼着做。本地开发完，执行一下deploy，就可以把链接扔给客户测试了。
