### ISSUE TITLE
如果打包完有个回调或者类似于钩子之类的就更好了

### ISSUE THREAD

**Issue by bashen1** [fwh1990/react-native-upload#15]
如果打包完有个回调或者类似于钩子之类的就更好了，这边想实现执行命令后，继续某些操作

**Comment by fwh1990** [comment]
可以大概描述一下吗？比如哪些地方可能会用到钩子，以及你理想中的实现方案

**Comment by bashen1** [comment]
我这边想编译完成后，关闭iOS编译时的Metro Bundler，并输出编译成功固定的蒲公英网址或二维码到页面
目前想到的解决方式：模块编译完成后，执行项目目录下的某个NodeJS脚本，来实现编译完成后的信息输出

**Comment by bashen1** [comment]
已经用后端的实现方式实现了
