### ISSUE TITLE
执行npx upload-pgy后只打包了androidapk，并没有上传到蒲公英

### ISSUE THREAD

**Issue by superchenwb** [fwh1990/react-native-upload#4]
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 47.91 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6 
      react-native: ^0.59.4 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

执行npx upload-pgy后只打包了androidapk，并没有上传到蒲公英

**Comment by fwh1990** [comment]
正常流程是先打包android和ios，再统一上传到蒲公英。terminal是否有报错信息导致进程终止？

**Comment by superchenwb** [comment]
没有任何信息。只有打包android成功的提示，随后任务就结束了

**Comment by superchenwb** [comment]
下面是我执行命令之后的提示

macdeMacBook-Pro:propertyapp chenwb$ npx upload-pgy
Starting a Gradle Daemon (subsequent builds will be faster)
Parallel execution with configuration on demand is an incubating feature.

> Configure project :app
Reading env from: .env

> Configure project :react-native-reanimated
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :react-native-smartrefreshlayout
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-syan-image-picker
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Task :realm:forwardDebugPort
adb: error: no devices/emulators found
===========================================================================
WARNING: Failed to automatically forward port 8083.
In order to use Realm in Chrome debugging mode, port 8083 must be forwarded
from localhost to the device or emulator being used to run the application.
You may need to add the appropriate flags to the command that failed:
    adb forward tcp:8083 tcp:8083
===========================================================================


> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, /Users/chenwb/propertyapp/android/app/build/generated/assets/react/release/index.android.bundle
info Done writing bundle output
info Copying 291 asset files
info Done copying assets

> Task :app:compileReleaseJavaWithJavac
注: /Users/chenwb/propertyapp/android/app/src/main/java/com/propertyapp/MainActivity.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

BUILD SUCCESSFUL in 2m 47s
527 actionable tasks: 49 executed, 478 up-to-date
/Users/chenwb/propertyapp
macdeMacBook-Pro:propertyapp chenwb$

**Comment by fwh1990** [comment]
看起来没什么问题。您是否愿意将环境放到github仓库中（业务代码先删除），然后我在本地测试，通过此法确定是macos的问题还是代码的问题。或者您发一份到我邮箱（531362022@qq.com）

**Comment by superchenwb** [comment]
https://github.com/superchenwb/uploaddemo.git 这是我的基础项目

**Comment by fwh1990** [comment]
您好，我发布了0.8.1处理了这个问题，您安装最新版本后再尝试。如果有效，请关闭issue。若仍有问题，请继续反馈。

补充两点：
1、iconfont尝试使用[这个库](https://github.com/iconfont-cli/react-native-iconfont-cli)，解决痛点
2、晚上早点睡

**Comment by superchenwb** [comment]
谢谢！fwh1990
