### ISSUE TITLE
如何和react-native-config一起使用

### ISSUE THREAD

**Issue by superchenwb** [fwh1990/react-native-upload#5]
我的项目中使用react-native-config，编译时需要指定一个配置文件。不知道该如何使用?

**Comment by fwh1990** [comment]
可以准备两个文件，比如 `.env.prod`和`.env.local`，开发时copy`.env.local`为.env文件，打包时copy`.env.prod`为.env文件。

**Comment by fwh1990** [comment]
正常来讲都是在`package.json`中预先定好脚本。
```json
{
  "scripts": {
    "start": "cp -f .env.local .env && react-native start",
    "deploy": "cp -f .env.prod .env && upload-pgy"
  }
}
```

**Comment by fwh1990** [comment]
在新版的react-native中，不再建议使用react-native-config，你可以直接在代码中使用node.js的语法`process.env.NODE_ENV`来处理配置：
```javascript
if (process.env.NODE_ENV === 'development') {
  // Do something
} else {
  // Do something
}
```

旧版本的RN可以使用[transform-inline-environment-variables](https://www.npmjs.com/package/babel-plugin-transform-inline-environment-variables)达到同样的效果

**Comment by fwh1990** [comment]
旧版本的RN可以使用[transform-inline-environment-variables](https://www.npmjs.com/package/babel-plugin-transform-inline-environment-variables)达到同样的效果

**Comment by superchenwb** [comment]
但是，我的项目可能需要打包不止两个环境，比如说有开发环境，多个测试环境，以及正式环境。还有就是有一些涉及原生的，比如说极光推送的app_key的配置之类的

**Comment by fwh1990** [comment]
之前是怎么处理的呢？

**Comment by superchenwb** [comment]
我是创建多个命令来打包的，这是我以前的项目的package.json里的scripts
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "dev": "react-native run-android",
    "build": "cd android && ./gradlew assembleRelease",
    "build:install": "cd android && SET ENVFILE=.env.test && ./gradlew installRelease",
    "build:test": "cd android && SET ENVFILE=.env.test && ./gradlew assembleRelease",
    "build:test:bash": "cd android && ENVFILE=.env.test ./gradlew assembleRelease",
    "build:production": "cd android && SET ENVFILE=.env.production && ./gradlew assembleRelease",
    "build:production:bash": "cd android && ENVFILE=.env.production ./gradlew assembleRelease",
    "clean": "cd android && ./gradlew clean",
    "test": "jest",
    "fix-modal": "node node_modules/react-native-modal-translucent/scripts/translucent-modal.js",
    "postinstall": "npm run fix-modal"
  },

**Comment by fwh1990** [comment]
根据shell的特性，您可以做适当的更改达到同样的效果
```json
{
  "scripts": {
    "deploy:test": "export ENVFILE=.env.test && upload-pgy",
    "deploy:production": "export ENVFILE=.env.production && upload-pgy"
  }
}
```
在scripts中定义的脚本会使用新的进程处理，使用export只影响新的进程和其子进程而不影响当前终端（父进程），与`ENVFILE=.env.test ./gradlew assembleRelease`这种写法效果一致

**Comment by superchenwb** [comment]
我以为export 只能放在cd android 之后。
